version: '3.8'

services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"

  backend:
    build:
      context: ./go-chat-backend
    ports:
      - "8080:8080"
    depends_on:
      - nats

  frontend:
    build:
      context: ./my-chat-app
    ports:
      - "3000:80"
    depends_on:
      - backend